language: node_js
node_js:
  - node
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.9
env:
  - CXX=g++-4.9
before_install:
  - npm explore npm -g -- npm install node-gyp@latest
install:
  - yarn
cache: yarn
script:
  - yarn lint
  - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
